### ISSUE TITLE
RAP Integration issue

### ISSUE THREAD

**Issue by akshaypardhanani** [AnkurGel/Instamojo-rb#5]
![log-instamojo-ticket](https://cloud.githubusercontent.com/assets/7630231/12347190/a4f9824c-bb81-11e5-8622-ada450e04b42.png)
I have a couple of problems with the integration for the RAP calls
I am using Rails 4.2.3 with Ruby 2.2.2p95
1.  Set API Keys
   api = Instamojo::API.new do |app|
   app.api_key = "api_key-you-received-from-api@instamojo.com"
   app.auth_token = "auth_token-you-received-from-api@instamojo.com"
   end

results in an error  which says undefined method each for '[MY_AUTH_TOKEN]' of class string. Howver I managed to resolve this by using (as in I stopped getting the error whether everything works or not I have no idea, reason for which is error 2 which I describe next).

api = Instamojo::API.new("api_key-you-received-from-api@instamojo.com", :auth_token => "auth_token-you-received-from-api@instamojo.com")

*\* Generate a client works fine **
1. REQUEST A PAYMENT
   payment_request = client.payment_request({amount:100, purpose: 'api', send_email: true, email: 'ankurgel+2@gmail.com', redirect_url: 'http://ankurgoel.com'})

gives me an error saying  undefined method `payment_request' for #Instamojo::Client:0xb397a9b0

In fact this is the case with all the methods i guess because i get it even for client.links_list 
the methods do not show up when i run " puts client.methods " either

Please can you help me out here? I do not understand what is going wrong.
Also after this works and I get the Json response, how do I redirect the user to the Instapay page so they can complete the payment?

EDIT:
Err after trying over the weekend I just reinstalled the gem and it seemed to work more or less.
client.payment_request still does not work unless I pass the values in the :key => value format. The aforementioned format returns a message from what I gather its telling me that the purpose field is required.

**Comment by AnkurGel** [comment]
Hi @akshaypardhanani 
Extremely sorry for late reply. I didn't get the mail notification for issue. 
I think you were using the old version of the [gem](https://rubygems.org/gems/Instamojo-rb). Do `gem -v` and check if it is pointing to 1.1.0? 
This should definitely work for you, without giving the error. 

``` ruby
api = Instamojo::API.new do |app|
  app.api_key = "api_key-you-received-from-api@instamojo.com"
  app.auth_token = "auth_token-you-received-from-api@instamojo.com"
end
```

If you are getting this, please give the stack-trace it gave, that will help me to debug. Also, please remember that after initializing the api above, you need to authenticate by generating the client as: `client = api.client`.

For 2nd issue, 

> client.payment_request still does not work unless I pass the values in the :key => value format
> Yes, this is bug. Block is not supported in `#payment_request`. I will be fixing that shortly in 1.1.1.  
> In Instamojo-rb, if any API call is erroneous, the library exposes the following:
> 
> ``` ruby
> client.payment_request({value: 100})
> unless client.response.success?
>   puts client.response.body && client.response.body[:message]
> end
> #=> "You do not have permission to perform this action."
> ```

Let me know if this helps you :)

**Comment by akshaypardhanani** [comment]
@AnkurGel  Hey  no problem. yes the gem version was the problem. When I installed it through bundler and old version of the gem is what got installed.
I fixed that by installing it with gem install Instamojo-rb then pointing the gemfile to use the correct version.
Thanks for the fixes :-)
